@ArchiveService_HostAddress = http://localhost:5028

GET {{ArchiveService_HostAddress}}/weatherforecast/
Accept: application/json

@ArchiveService_HostAddress = http://localhost:7001

GET {{ArchiveService_HostAddress}}/api/ads
Accept: Application/json
###
